name: base
channels:
  - conda-forge
dependencies:
  - cctbx-base=2022.4
  - openbabel=3.1.1
  - pip
  - pip:
      - nanome==0.40.3
      - griddataformats==0.7.0
      - PyMCubes==0.1.2
      - pyfqmr==0.1.2
      - randomcolor==0.4.4.6
      - scipy==1.7.3
      - numpy==1.21.6
      - matplotlib==3.5.3
      - requests==2.28.1
      - aiohttp
      # - -e ./nanome-sdk
      

